# Generated by Django 4.1.5 on 2023-02-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_team_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(default='no', upload_to='photo/%y/%m/%d'),
        ),
    ]
